export default {
  content: [
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "primary-container": "#2d4739",
        "surface-container": "#e5eeff",
        "surface": "#f8f9ff",
        "background": "#f8f9ff",
        "primary-fixed-dim": "#b0cdbb",
        "on-surface": "#121c28",
        "tertiary-fixed": "#e3e2e2",
        "secondary-container": "#dce2f3",
        "on-primary-fixed-variant": "#324c3e",
        "secondary-fixed-dim": "#c0c7d6",
        "on-background": "#121c28",
        "error-container": "#ffdad6",
        "on-primary-container": "#98b5a3",
        "on-error-container": "#93000a",
        "on-surface-variant": "#424844",
        "on-tertiary-fixed": "#1a1c1c",
        "secondary-fixed": "#dce2f3",
        "inverse-surface": "#27313e",
        "surface-container-low": "#eef4ff",
        "primary-fixed": "#ccead6",
        "secondary": "#585f6c",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-fixed-variant": "#464747",
        "inverse-primary": "#b0cdbb",
        "surface-dim": "#d1dbec",
        "tertiary-container": "#414242",
        "surface-tint": "#496455",
        "surface-container-high": "#dfe9fa",
        "on-secondary-container": "#5e6572",
        "on-primary-fixed": "#062014",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "outline-variant": "#c2c8c2",
        "surface-bright": "#f8f9ff",
        "primary": "#173124",
        "tertiary": "#2b2c2c",
        "on-tertiary-container": "#aeaeae",
        "tertiary-fixed-dim": "#c7c6c6",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#404754",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#151c27",
        "surface-variant": "#d9e3f4",
        "surface-container-highest": "#d9e3f4",
        "outline": "#727973"
      },
    },
  },
  plugins: [],
};
